customhost = "employee.chqgsdykgslv.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "bait3273"
customdb = "employee"
custombucket = "chinyantong-employee"
customregion = "us-east-1"
